# 开源项目地址 https://github.com/lowlighter/metrics
# 基于配置文件二次修改 https://github.com/sun0225SUN/sun0225SUN/blob/main/.github/workflows/metrics.yml

name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 基础信息
      - name: base
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/base.svg
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: chenskiro
          template: classic
          config_timezone: Asia/JiangSu
          base: "header, activity, community, repositories"
          # 🧮 Repositories traffic
          plugin_traffic: yes
          # 👨‍💻 Lines of code changed
          plugin_lines: yes
          # 🙋 Introduction
          plugin_introduction: yes
          # 🎫 Gists
          plugin_gists: yes
          # 💫 Star lists
          plugin_starlists: yes
          plugin_starlists_limit_repositories: 2
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 8
          plugin_starlists_only: Awesome
          # 📌 Starred topics
          plugin_topics: yes
          plugin_topics_mode: labels
          plugin_topics_sort: activity
          plugin_topics_limit: 0
          # 📰 Recent activity
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create, wiki

      # 🕹️ Steam
      - name: Steam
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/metrics.plugin.steam.svg
          token: NOT_NEEDED
          base: ""
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: "76561199205543917"
          plugin_steam_sections: player, recently-played
          plugin_steam_recent_games_limit: 5
          plugin_steam_games_ignored: 431960

      # anilist
      - name: Favorites anime and currently watching
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/metrics.plugin.anilist.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: chenskiro
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 8


      
      # 🈷️ Languages activity
      - name: Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/languages.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 4
          plugin_languages_analysis_timeout: 15

      # ✨ Stargazers   
      - name: Using chartist charts
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/stargazers.chartist.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts_type: chartist

      # 🌟 Recently starred repositories
      - name: Recently starred
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/stars.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 10
          
      # 💡 Coding habits and activity
      - name: Recent activity charts
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: Europe/Paris
        
          
      # 🎭 Comment reactions
      - name: Comment reactions
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/reactions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage

      # 🧑‍🤝‍🧑 People    
      - name: Followers
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/people.followers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_people: yes
          plugin_people_limit: 500
          plugin_people_size: 36
          plugin_people_types: followers
          
      # 📓 Featured repositories
      - name: Pinned repositories
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/repositories.pinned.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_repositories: yes
          plugin_repositories_pinned: 2

      # 💬 Discussions
      - name: GitHub Discussions
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/discussions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_discussions: yes
          plugin_discussions_categories_limit: 8       
   
      # 📆 Commit calendar
      - name: Full history calendar
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/calendar.full.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0

      # 🏆 Achievements
      - name: Compact display
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/achievements.compact.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X

      # 📰 Recent activity
      - name: Recent activity
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
   
      # 🗨️ Stack Overflow
      - name: Top answers from stackoverflow
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/stackoverflow.svg
          token: NOT_NEEDED
          base: ""
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 1
          plugin_stackoverflow_sections: answers-top
          plugin_stackoverflow_limit: 2
          
      # 📌 Starred topics
      - name: Icons
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/metrics.plugin.topics.icons.svg
          token: NOT_NEEDED
          base: ""
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons
          plugin_topics_sort: activity
